id: AB841736D
title: 'Freedom from All Adversity: A Sur Offering to Harmful Influences, Obstacle-Makers
  and Elemental Spirits'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:01:01.623426
  last_modified_at: 2022-03-01 05:01:01.623430
