id: AB841736D
title: Töpa Gyatsoma Offering Prayer
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:01:01.636546
  last_modified_at: 2022-03-01 05:01:01.636549
