id: AB841736D
title: 'The Wish-Granting King of Jewels: An Essential Garland of Offerings'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:01:01.635600
  last_modified_at: 2022-03-01 05:01:01.635603
