id: AB841736D
title: Great Clouds of First-Portion Offerings for Prosperity
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - nl
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:01:01.626610
  last_modified_at: 2022-03-01 05:01:01.626617
