id: AB841736D
title: Offering to the NÄgas of Gangtok
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:01:01.631146
  last_modified_at: 2022-03-01 05:01:01.631148
