id: AB841736D
title: Offering the Eight Auspicious Substances and Seven Emblems of Royalty
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:01:01.629788
  last_modified_at: 2022-03-01 05:01:01.629792
