id: AB841736D
title: The Verse for Offering Water from the Pure Vision, An Ocean of Accomplishments
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - nl
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:01:01.634328
  last_modified_at: 2022-03-01 05:01:01.634331
