id: AB841736D
title: A Means of Offering Sur to the Damsi, Gyalgong and Others
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:01:01.619130
  last_modified_at: 2022-03-01 05:01:01.619137
